app/routes.py
from flask import Blueprint, render_template, request, Response, jsonify
from app.models import Product, Location, db, ProductMovement
from sqlalchemy import func
from datetime import datetime

# Define the Blueprint instance
app = Blueprint('app', __name__)


# End Points for the UI operations
@app.route('/product/<location>')
def product(location):
    products = Location.query \
        .join(Product, Product.id == Location.product_id) \
        .filter(Location.location_name == location) \
        .with_entities(Location.id, Product.product_name, Location.product_id, Location.quantity, Location.location_name) \
        .all()
    print(products)

    # Group the location names and return them as a JSON response
    grouped_locations = db.session.query(Location.location_name, func.sum(Location.quantity).label('total_quantity')) \
        .group_by(Location.location_name) \
        .all()

    location_names = [location_name for location_name, _ in grouped_locations]

    print(location_names)

    result_json = []
    for id,  product_name, product_id, quantity, location_name in products:
        result_json.append({
            'location_id': id,
            'product_name': product_name,
            'product_id': product_id,
            'quantity': quantity,
            'location_name': location_name
        })

        print(result_json)

    return render_template('product.html', products=result_json, location_name=location, location_names=location_names)


@app.route('/update_product/', methods=['PUT'])
def update_product():
    # Get the data from the request form
    location_id = request.form.get('id')
    new_product_name = request.form.get('product_name')
    new_quantity = request.form.get('quantity')
    print(location_id, new_product_name, new_quantity)

    try:
        # Find the location with the given product_id and location_name
        location = Location.query.filter_by(id=location_id).first()
        print(location)
        if location:
            # Update the product_name and quantity for the location
            location.product.product_name = new_product_name
            location.quantity = new_quantity

            # Commit the changes to the database
            db.session.commit()

            # Return the updated location data as JSON response
            return jsonify({
                'id': location.id,
                'product_name': location.product.product_name,
                'quantity': location.quantity
            })
        else:
            # Handle the case when the location is not found
            return jsonify({'error': 'Location not found or product_id is not associated with the given location.'}), 404
    except Exception as e:
        # Handle any other exception that might occur during the update
        print("=================", e)
        return jsonify({'error': 'An error occurred during the update.'}), 500


@app.route('/add_product/', methods=['POST'])
def add_product():
    # Get the data from the request form
    location = request.form.get('location')
    product_name = request.form.get('product_name')
    quantity = request.form.get('quantity')

    try:
        # Create a new Product object with the given data
        new_product = Product(product_name=product_name)

        # Add the new product to the database
        db.session.add(new_product)
        db.session.commit()

        # Create a new Location object associated with the new product
        new_location = Location(product=new_product,
                                quantity=quantity, location_name=location)

        # Add the new location to the database
        db.session.add(new_location)
        db.session.commit()
        res = {
            'id': new_location.id,
            'product_name': new_product.product_name,
            'quantity': new_location.quantity,
            'location_name': new_location.location_name
        }

        print(res)
        # Return the new product and location data as JSON response
        return jsonify(res)
    except Exception as e:
        # Handle any other exception that might occur during the insertion
        print("================", e)
        return jsonify({'error': 'An error occurred while adding the product.'}), 500


def move_product_between_locations(product_id, from_location, to_location, quantity_to_move):
    try:
        # Check if the product exists in the source location
        source_location = Location.query.filter_by(
            location_name=from_location).first()
        product_in_source = None
        if source_location:
            product_in_source = Product.query.filter_by(id=product_id).join(
                Location).filter_by(id=source_location.product_id).first()

        if not product_in_source or (source_location.quantity < quantity_to_move):
            raise ValueError(
                "Product not found in the source location or insufficient quantity.")

        # Check if the product exists in the target location
        target_location = Location.query.filter_by(
            location_name=to_location).first()

        if target_location:
            # If the product already exists in the target location, update its quantity
            new_quantity_in_target = target_location.quantity + quantity_to_move
            target_location.quantity = new_quantity_in_target
        else:
            # If the product doesn't exist in the target location, create a new entry
            target_location = Location(
                location_name=to_location, quantity=quantity_to_move, product_id=product_id)
            db.session.add(target_location)

        # Update the quantity in the source location
        new_quantity_in_source = source_location.quantity - quantity_to_move
        source_location.quantity = new_quantity_in_source

        # Record the product movement in the ProductMovement table
        movement = ProductMovement(
            product_id_fk=product_id,
            from_location_id=source_location.id,
            to_location_id=target_location.id,
            quantity=quantity_to_move,
            time_stamp=datetime.utcnow()
        )
        db.session.add(movement)

        db.session.commit()
        return {"success": True, "to_location": to_location}
    except Exception as e:
        return {"success": False, "error": str(e)}


# Move API route
@app.route('/move_product/', methods=['POST'])
def move_product():
    try:
        # Get data from the request
        product_id = request.form.get('product_id')
        from_location = request.form.get('from_location')
        to_location = request.form.get('to_location')
        quantity_to_move = int(request.form.get('quantity'))

        print("=================================", product_id,
              to_location, from_location, quantity_to_move)

        # Perform the product movement and update quantities
        result = move_product_between_locations(
            product_id, from_location, to_location, quantity_to_move)
        print(result)

        if result["success"]:
            # If the movement is successful, return the target location in the response
            return jsonify({"to_location": to_location})
        else:
            # If there is an error in the movement, return the error message in the response
            return jsonify({"error": result["error"]}), 400

    except Exception as e:
        print(e)
        return jsonify({"error": str(e)}), 500


@app.route('/product_balance_report', methods=['GET'])
def product_balance_report():
    try:
        # Fetch the product balance in each location
        product_locations = db.session.query(Product.product_name, Location.location_name, Location.quantity).\
            join(Location, Product.id == Location.product_id).all()

        # Render the report template with the data
        return render_template('report.html', product_locations=product_locations)
    except Exception as e:
        # Handle exceptions if needed
        return render_template('error.html', error=str(e))


@app.route('/generate_csv_report', methods=['GET'])
def generate_csv_report():
    try:
        # Fetch the product balance in each location
        product_locations = db.session.query(Product.product_name, Location.location_name, Location.quantity).\
            join(Location, Product.id == Location.product_id).all()

        # Create a CSV string
        csv_data = "Product,Warehouse,Qty\n"
        for product, warehouse, qty in product_locations:
            csv_data += f"{product},{warehouse},{qty}\n"

        # Generate the CSV file response
        response = Response(csv_data, content_type='text/csv')
        response.headers['Content-Disposition'] = 'attachment; filename=product_balance_report.csv'
        return response
    except Exception as e:
        # Handle exceptions if needed
        return render_template('error.html', error=str(e))


@app.route('/product_movement_details', methods=['GET'])
def product_movement_details():
    try:
        # Fetch the product movement data from the database
        product_movements = ProductMovement.query.all()

        # Render the movement_report template with the data
        return render_template('movement_report.html', product_movements=product_movements)
    except Exception as e:
        # Handle exceptions if needed
        return render_template('error.html', error=str(e))


@app.route('/generate_csv_movement_report', methods=['GET'])
def generate_csv_movement_report():
    try:
        # Fetch the product movement data from the database
        product_movements = ProductMovement.query.all()

        # Create a CSV string
        csv_data = "Product,From Warehouse,To Warehouse,Qty Moved,Timestamp\n"
        for movement in product_movements:
            csv_data += f"{movement.product.product_name},{movement.from_location.location_name},{movement.to_location.location_name},{movement.quantity},{movement.time_stamp}\n"

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- External Css Link -->
    <link rel="stylesheet" href="/static/style.css">

    <!-- Bootstrap CSS Link -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">

    <!-- Title of my Page -->
    <title>{% block title %}{% endblock %}</title>

</head>
<body class="container-fluid">
    <div class="baseStructClass">

        <!-- NavBar of the page -->
        <navbar>
            <nav class="navbar navbar-expand-lg bg-body-tertiary">
                <div class="container-fluid bg-navbar">
                  <a class="navbar-brand" href="/"> 
                    <img src="/static/uploads/Logo.png" alt="Logo" width="40" height="40" class="d-inline-block align-text-center"> 
                  </a>
                  <button class="navbar-toggler" id="button-color" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon toggler-color"></span>
                  </button>
                  <div class="collapse navbar-collapse justify-content-end" id="navbarNav">
                    <ul class="navbar-nav ">
                      <li class="nav-item">
                        <a class="nav-link text-white" href="/">Home</a>
                      </li>
                      <li class="nav-item d-flex align-items-center">
                        <select class="border-0 bg-navbar text-white">
                            <option class="nav-link">Locations</option>
                            <option><a class="nav-link" href="/coimbatore">Coimbatore</a></option>
                            <option><a class="nav-link" href="/chennai">Chennai</a></option>
                            <option><a class="nav-link" href="/thirunelveli">Thirunelveli</a></option>
                        </select>
                      </li>
                    </ul>
                  </div>
                </div>
              </nav>
        </navbar>

        <!-- Sidearea of the page -->
        <aside>
            <div class="d-flex justify-content-center">
                <div class="card adminClass" style="width: 8rem;">
                    <img src="/static/uploads/adminimg.png" class="card-img-top" alt="img">
                    <div class="card-body">
                      <h5 class="card-title">Admin</h5>
                    </div>
                    <hr>
                </div>
            </div>
            <div class="w-100 d-flex justify-content-center">
              <a href="{{ url_for('app.product_balance_report')}}" class="btn btn-danger m-3">Generate Report</a>
              <a href="{{ url_for('app.product_movement_details')}}" class="btn btn-success m-3">Movement Details</a>
          </div>
        </aside>

        <!-- Main content of the page -->
        <main>{% block content %}{% endblock %}</main>

        <!-- Footer of the page -->
        <footer>
            <div class="container">
              <div class="footer-content row">
                <!-- Footer logo or name -->
                <div class="footer-logo col-2 d-flex align-items-center">
                    <img src="/static/uploads/tasklogo.jpg" alt="Logo" width="100" height="100" class="d-inline-block align-text-center border border-white"> 
                </div>
                
                <div class="col-10 p-2">
                    <!-- Contact information -->
                    <div class="contact-info text-end text-white lh-1">
                      <p>Email: inventory@gmail.com</p>
                      <p>Phone: +91-9360 790 855</p>
                      <p>&copy; 2023 Your Company. All rights reserved.</p>
                    </div>
                </div>
              </div>
            </div>
          </footer>
    </div>


    <!-- Scripts Link For Bootstrap -->
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.min.js" integrity="sha384-Rx+T1VzGupg4BHQYs2gCW9It+akI2MM/mndMCy36UVfodzcJcF0GGLxZIzObiEfa" crossorigin="anonymous"></script>

</body>
</html>

templates/error.html
<!DOCTYPE html>
<html>
<head>
    <title>Error</title>
</head>
<body>
    <h1>An error occurred:</h1>
    <p>{{ error }}</p>
</body>
</html>

templates/index.html
{% extends "base.html" %}
{% block title %}Inventory Management{% endblock %}
{% block content %}
<div class="row row-cols-1 row-cols-md-3 g-4 p-3">
    <div class="col cardsMainClass">
    <a href="{{ url_for('app.product', location='coimbatore') }}"><div class="card">
        <img src="/static/uploads/coimbatore.jpg" class="card-img-top" alt="coimbatore">
        <div class="card-body">
          <h5 class="card-title">Gandhipuram Warehouse</h5>
          <p class="card-text">This warehouse distributes to north of whole Tamil Nadu</p>
        </div>
      </div></a>
    </div>
    <div class="col cardsMainClass">
      <a href="{{ url_for('app.product', location='chennai') }}"><div class="card">
        <img src="/static/uploads/chennai.jpg" class="card-img-top" alt="chennai">
        <div class="card-body">
          <h5 class="card-title">Velachery Warehouse</h5>
          <p class="card-text">This warehouse distributes to West of whole Tamil Nadu</p>
        </div>
      </div></a>
    </div>
    <div class="col cardsMainClass">
    <a href="{{ url_for('app.product', location='thirunelveli') }}"><div class="card">
        <img src="/static/uploads/thirunelveli.jpg" class="card-img-top" alt="thirunelveli">
        <div class="card-body">
          <h5 class="card-title">Thirunelveli Junction Warehouse</h5>
          <p class="card-text">This warehouse distributes to South of whole Tamil Nadu</p>
        </div>
      </div></a>
    </div>
  </div>
{% endblock %}

templates/movement_report.html
{% extends 'base.html' %}

{% block content %}
    <h1 class="text-center mb-3">Product Export & Import Report</h1>
    <table class="table table-dark table-striped">
        <thead>
            <tr>
                <th>Product</th>
                <th>From Warehouse</th>
                <th>To Warehouse</th>
                <th>Qty Moved</th>
                <th>Timestamp</th>
            </tr>
        </thead>
        <tbody>
            {% for movement in product_movements %}
                <tr>
                    <td>{{ movement.product.product_name }}</td>
                    <td>{{ movement.from_location.location_name }}</td>
                    <td>{{ movement.to_location.location_name }}</td>
                    <td>{{ movement.quantity }}</td>
                    <td>{{ movement.time_stamp }}</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
    <a href="{{ url_for('app.generate_csv_movement_report') }}" class="btn btn-primary">Download CSV</a>
{% endblock %}

templates/product.html
<!-- templates/home.html -->
{% extends 'base.html' %}

{% block title %}Product Page{% endblock %}
{% block content %}
<h1 class="text-center mb-3">Product Details - <span id=location-val>{{location_name}}</span></h1>

<table class="table table-dark">
    <thead>
        <tr>
            <th>Product Name</th>
            <th>Product Quantity</th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody>
        {% for product in products %}
        <tr>
            <td contenteditable="false" class="editable" data-field="product_name" data-id="{{ product.location_id }}">{{
                product.product_name }}</td>
            <td contenteditable="false" class="editable" data-field="quantity" data-id="{{ product.location_id }}">{{
                product.quantity }}</td>
            <td>
                <button class="btn btn-info btn-edit" data-id="{{ product.location_id }}">Edit</button>
                <button class="btn btn-success btn-save" data-id="{{ product.location_id }}"
                    style="display: none;">Save</button>
                <button class="btn btn-warning btn-move" data-id="{{ product.product_id }}"
                    data-location="{{ product.location_name }}" data-quantity="{{ product.quantity }}">Move</button>
                <input type="hidden" class="product-quantity" value="{{ product.quantity }}">
                <input type="hidden" id="product-id" value="{{ product.product_id }}">            
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>
<button class="btn btn-primary btn-add" data-location="{{location_name}}">Add New</button>

<!-- Modal for move product -->
<div class="modal fade" id="moveProductModal" tabindex="-1" aria-labelledby="moveProductModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="moveProductModalLabel">Move Product</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <div class="mb-3">
                    <label for="target-location" class="form-label">Select Target Location:</label>
                    <select class="form-select" id="target-location">
                        {% for location in location_names if not location == location_name %}
                        <option value="{{ location }}">{{ location }}</option>
                        {% endfor %}
                    </select>
                </div>
                <div class="mb-3">
                    <label for="quantity" class="form-label">Available Quantity: <span id="available-quantity"></span></label>
                    <input type="number" class="form-control" id="quantity" min="1" max="{{ currentQuantity }}"
                        placeholder="Enter quantity">
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
                <button type="button" class="btn btn-primary" id="confirmMove">Move</button>
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block scripts %}
<script>
    $(document).ready(function () {
        // Handle Edit button click
        $('.btn-edit').on('click', function () {
            var button = $(this);
            var productId = button.data('id');

            var row = button.closest('tr');

            // Switch the cells to edit mode
            row.find('[data-field="product_name"]').attr('contenteditable', true).focus();
            row.find('[data-field="quantity"]').attr('contenteditable', true).focus();

            // Hide the Edit button and show the Save button
            button.hide();
            row.find('.btn-save').show();
        });

        // Handle Save button click
        $('.btn-save').on('click', function () {
            var button = $(this);
            var productId = button.data('id');
            var row = button.closest('tr');

            // Get the updated data from the editable cells
            var productName = row.find('[data-field="product_name"]').text();
            var quantity = row.find('[data-field="quantity"]').text();

            // Make an AJAX request to update the data
            $.ajax({
                url: '/update_product/',
                type: 'PUT',
                data: {
                    id: productId,
                    product_name: productName,
                    quantity: quantity
                },
                success: function (response) {
                    // Update the table cell with the new data
                    row.find('[data-field="product_name"]').text(response.product_name);
                    row.find('[data-field="quantity"]').text(response.quantity);

                    // Switch the cells back to non-edit mode
                    row.find('[data-field="product_name"]').attr('contenteditable', false);
                    row.find('[data-field="quantity"]').attr('contenteditable', false);

                    // Show the Edit button and hide the Save button
                    row.find('.btn-edit').show();
                    button.hide();

                    console.log("Updated");
                    alert("Product updated successfully");
                },
                error: function (error) {
                    console.log('Error:', error);
                }
            });

        });
        // Handle Add New button click
        $('.btn-add').on('click', function () {
            // Create a new row and append it to the table body
            var newRow = $('<tr>');
            newRow.append('<td contenteditable="true" class="editable" data-field="product_name"></td>');
            newRow.append('<td contenteditable="true" class="editable" data-field="quantity"></td>');
            newRow.append('<td><button class="btn btn-success btn-save-new">Save</button></td>');
            newRow.appendTo('.table tbody');

            // Switch the new cells to edit mode
            newRow.find('[data-field="product_name"]').attr('contenteditable', true).focus();
            newRow.find('[data-field="quantity"]').attr('contenteditable', true).focus();

            // Hide the "Add New" button
            $(this).hide();

            // Show the "Save" button for the new row
            newRow.find('.btn-save-new').show();
        });

        // Handle Save New button click
        $(document).on('click', '.btn-save-new', function () {
            var button = $(this);
            var row = button.closest('tr');
            var locationName = $('#location-val').text().trim();
            console.log(locationName);
            var location = locationName;

            // Get the data from the new row
            var productName = row.find('[data-field="product_name"]').text();
            var quantity = row.find('[data-field="quantity"]').text();

            // Make an AJAX request to insert the data into the database
            $.ajax({
                url: '/add_product/',
                type: 'POST',
                data: {
                    location: location,
                    product_name: productName,
                    quantity: quantity
                },
                success: function (response) {
                    // Update the table cell with the new data
                    row.find('[data-field="product_name"]').text(response.product_name);
                    row.find('[data-field="quantity"]').text(response.quantity);

                    // Switch the cells back to non-edit mode
                    row.find('[data-field="product_name"]').attr('contenteditable', false);
                    row.find('[data-field="quantity"]').attr('contenteditable', false);

                    // Show the "Add New" button
                    $('.btn-add').show();

                    console.log("Added");
                    alert("Product added successfully");
                    location.reload();
                },
                error: function (error) {
                    console.log('Error:', error);
                }
            });
        });

        // Handle Move button click
        $('.btn-move').on('click', function () {
            var button = $(this);
            var currentLocation = button.data('location');
            var currentQuantity = button.data('quantity');

            // Show the moveProductModal and populate available quantity
            $('#available-quantity').text(currentQuantity); // Set available quantity in the modal
            $('#quantity').val(''); // Reset the quantity input
            $('#moveProductModal').modal('show');

            // Click event for the "Move" button inside the modal
            $('#confirmMove').on('click', function () {
                var productId = parseInt($('#product-id').val());
                var quantityToMove = parseInt($('#quantity').val());
                var targetLocation = $('#target-location').val();
                console.log(productId);

                if (isNaN(quantityToMove) || quantityToMove <= 0 || quantityToMove > currentQuantity) {
                    alert('Invalid quantity. Please enter a valid quantity.');
                    return;
                }

                // Make an AJAX request to move the product
                $.ajax({
                    url: '/move_product/',
                    type: 'POST',
                    data: {
                        product_id: productId,
                        from_location: currentLocation,
                        to_location: targetLocation,
                        quantity: quantityToMove
                    },
                    success: function (response) {
                        // Update the quantity in the current row
                        button.data('quantity', currentQuantity - quantityToMove);
                        button.attr('data-quantity', currentQuantity - quantityToMove);

                        // Show the updated quantity in the row
                        button.closest('tr').find('.editable[data-field="quantity"]').text(currentQuantity - quantityToMove);

                        alert(`Successfully moved ${quantityToMove} items from ${currentLocation} to ${response.to_location}.`);
                        window.location.reload()
                    },
                    error: function (error) {
                        console.log('Error:', error);
                        alert('Failed to move the product. Please try again later.');
                    }
                });

                // Close the modal after moving the product
                $('#moveProductModal').modal('hide');
            });
        });
    });
</script>
{% endblock %}

templates/report.html
{% extends 'base.html' %}

{% block content %}
    <h1 class="text-center mb-3">Total Product Availability Report</h1>
    <table class="table table-dark table-striped">
        <thead>
            <tr>
                <th>Product</th>
                <th>Warehouse</th>
                <th>Qty</th>
            </tr>
        </thead>
        <tbody>
            {% for product, warehouse, qty in product_locations %}
                <tr>
                    <td>{{ product }}</td>
                    <td>{{ warehouse }}</td>
                    <td>{{ qty }}</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
    <a href="{{ url_for('app.generate_csv_report') }}" class="btn btn-primary">Download CSV</a>
{% endblock %}